In [4]:
import pandas as pd

df = pd.read_csv(r'C:\Users\user\Downloads\Dataset for Data Analyticsp1.csv')
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,1/4/2023,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,8/23/2024,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2/27/2024,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,10/15/2023,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,5/8/2025,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [5]:
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,6/20/2024,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,3/4/2024,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,7/13/2023,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,8/22/2024,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,6/11/2023,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [7]:
print(df.isnull().sum())  # missing values check

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [8]:
print(df.dtypes)       # column types check karo

OrderID                str
Date                   str
CustomerID             str
Product                str
Quantity             int64
UnitPrice          float64
ShippingAddress        str
PaymentMethod          str
OrderStatus            str
TrackingNumber         str
ItemsInCart          int64
CouponCode             str
ReferralSource         str
TotalPrice         float64
dtype: object

In [9]:
print(df.shape)

(1200, 14)

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
print("Duplicate OrderIDs:", df['OrderID'].duplicated().sum())

Duplicate OrderIDs: 0

In [12]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

In [13]:
df['ReferralSource'] = df['ReferralSource'].fillna('Unknown')

In [15]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   str
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), str(10)
memory usage: 131.4 KB

In [17]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [18]:
print(df['OrderStatus'].unique())

<StringArray>
['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending']
Length: 5, dtype: str

In [19]:
print(df['ReferralSource'].unique())

<StringArray>
['Instagram', 'Referral', 'Email', 'Facebook', 'Google']
Length: 5, dtype: str

In [20]:
print(df['CouponCode'].unique())

<StringArray>
['SAVE10', 'FREESHIP', 'No Coupon', 'WINTER15']
Length: 4, dtype: str

In [21]:
print(df['PaymentMethod'].unique())

<StringArray>
['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash']
Length: 5, dtype: str

In [24]:
df['OrderStatus'] = df['OrderStatus'].str.strip().str.title()

In [26]:
df['PaymentMethod'] = df['PaymentMethod'].str.strip().str.title()

In [27]:
print(df[['Quantity','UnitPrice','TotalPrice']].describe())

          Quantity    UnitPrice   TotalPrice
count  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750  1053.968300
std       1.407557   197.177146   819.856558
min       1.000000    11.390000    11.390000
25%       2.000000   186.062500   410.520000
50%       3.000000   364.210000   823.615000
75%       4.000000   521.570000  1578.475000
max       5.000000   699.930000  3456.400000

In [28]:
print(df['Date'].min(), df['Date'].max())

1/1/2023 9/9/2024

In [29]:
print("Negative Quantity:", (df['Quantity'] <= 0).sum())
print("Negative UnitPrice:", (df['UnitPrice'] <= 0).sum())

Negative Quantity: 0
Negative UnitPrice: 0

In [30]:
df['CalculatedPrice'] = df['Quantity'] * df['UnitPrice']
mismatch = df[abs(df['CalculatedPrice'] - df['TotalPrice']) > 1]
print("Mismatched rows:", len(mismatch))

Mismatched rows: 0